apiVersion: v1
kind: Secret
metadata:
  name: jsc-gs-secret
  namespace: jsc-ns
type: Opaque
data:
  callback_url: {{ your callback URL base64 encoded }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jsc-gs-credentials
  namespace: jsc-ns
type: Opaque
data:
  credentials.json: {{ your credentials.json base64 encoded }}
